(()=>{"use strict";const {$,$$}=window.AL;
function pathPts(pts,x,y){return pts.map((p,i)=>`${i?'L':'M'}${x(p[0]).toFixed(1)},${y(p[1]).toFixed(1)}`).join(' ')}
function drawFamily(){const beta=+$('#curveBeta').value,hi=+$('#curveIb').value;$('#curveBetaTxt').textContent=beta;$('#curveIbTxt').textContent=hi;const a=window.AL.axes(0,12,0,Math.max(8,beta*60e-6*1000*1.25),'VCE (V)','IC (mA)');let h=a.h;h+=`<rect x="${a.x(0)}" y="${a.T}" width="${a.x(.35)-a.x(0)}" height="${a.gh}" fill="var(--red2)" opacity=".7"/><rect x="${a.x(.35)}" y="${a.T}" width="${a.x(12)-a.x(.35)}" height="${a.gh}" fill="var(--green2)" opacity=".38"/>`;
for(let ib=0;ib<=60;ib+=10){let pts=[];for(let v=0;v<=12;v+=.08){const flat=beta*(ib*1e-6)*1000;const ic=flat*(1-Math.exp(-v/.13))*(1+v/180);pts.push([v,ic])}const stroke=ib===hi?'var(--red)':'var(--blue)',sw=ib===hi?4:2;h+=`<path d="${pathPts(pts,a.x,a.y)}" fill="none" stroke="${stroke}" stroke-width="${sw}" opacity="${ib===hi?1:.62}"/><text x="${a.x(11.2)}" y="${a.y(pts[pts.length-1][1])-4}" font-size="10" fill="${stroke}">${ib} µA</text>`}h+=`<text x="${a.x(.16)}" y="${a.T+18}" text-anchor="middle" font-size="11" fill="var(--red)">SAT</text><text x="${a.x(7)}" y="${a.T+18}" font-size="11" fill="var(--green)">ACTIVA</text><text x="${a.x(9)}" y="${a.y(.2)}" font-size="11" fill="var(--muted)">IB=0 ≈ corte</text>`;$('#bjtCurveChart').innerHTML=h}
['curveBeta','curveIb'].forEach(id=>$('#'+id)?.addEventListener('input',drawFamily));drawFamily();

function solve(v){const ib=Math.max(0,(v.Vbb-v.Vbe)/(v.Rb*1000));const activeIc=v.beta*ib;const icsat=Math.max(0,(v.Vcc-v.Vces)/(v.Rc*1000));let region,ic,vce;if(ib<=1e-12){region='cutoff';ic=0;vce=v.Vcc}else if(activeIc>=icsat){region='saturation';ic=icsat;vce=v.Vces}else{region='active';ic=activeIc;vce=v.Vcc-ic*v.Rc*1000}const ie=ic+ib,pc=ic*vce;return{...v,ib,activeIc,icsat,region,ic,vce,ie,pc}}
function simVals(){return{Vbb:+$('#bVbb').value,Rb:+$('#bRb').value,Vcc:+$('#bVcc').value,Rc:+$('#bRc').value,beta:+$('#bBeta').value,Vbe:+$('#bVbe').value,Vces:+$('#bVces').value}}
function drawLoad(el,v,q,includeCurves=true){const ymax=Math.max(1,v.Vcc/(v.Rc*1000)*1000*1.2),a=window.AL.axes(0,v.Vcc*1.08,0,ymax,'VCE (V)','IC (mA)');let h=a.h;h+=`<rect x="${a.x(0)}" y="${a.T}" width="${Math.max(3,a.x(Math.min(.35,v.Vcc))-a.x(0))}" height="${a.gh}" fill="var(--red2)" opacity=".55"/>`;if(includeCurves){for(let ib=0;ib<=60;ib+=10){let pts=[];for(let x=0;x<=v.Vcc*1.05;x+=v.Vcc/120){let ic=v.beta*(ib*1e-6)*1000*(1-Math.exp(-x/.13))*(1+x/180);pts.push([x,Math.min(ic,ymax*1.05)])}h+=`<path d="${pathPts(pts,a.x,a.y)}" fill="none" stroke="var(--blue)" stroke-width="1.6" opacity=".35"/>`}}
const load=[[0,v.Vcc/v.Rc],[v.Vcc,0]];h+=`<path d="${pathPts(load,a.x,a.y)}" fill="none" stroke="var(--amber)" stroke-width="4"/><circle cx="${a.x(q.vce)}" cy="${a.y(q.ic*1000)}" r="7" fill="var(--red)"/><text x="${a.x(q.vce)+10}" y="${a.y(q.ic*1000)-10}" fill="var(--red)" font-size="13">Q · ${q.region==='active'?'activa':q.region==='saturation'?'sat.':'corte'}</text>`;el.innerHTML=h}
const baseExample={Vbb:5,Rb:180,Vcc:12,Rc:2.2,beta:120,Vbe:.7,Vces:.2};drawLoad($('#loadLineChart'),baseExample,solve(baseExample),true);

function updateSim(){const v=simVals(),q=solve(v);$('#bVbbTxt').textContent=v.Vbb.toFixed(1);$('#bRbTxt').textContent=v.Rb.toFixed(0);$('#bVccTxt').textContent=v.Vcc.toFixed(1);$('#bRcTxt').textContent=v.Rc.toFixed(2);$('#bBetaTxt').textContent=v.beta;$('#bVbeTxt').textContent=v.Vbe.toFixed(2);$('#bVcesTxt').textContent=v.Vces.toFixed(2);$('#bIb').textContent=(q.ib*1e6).toFixed(2)+' µA';$('#bIc').textContent=(q.ic*1e3).toFixed(2)+' mA';$('#bIe').textContent=(q.ie*1e3).toFixed(2)+' mA';$('#bVce').textContent=q.vce.toFixed(2)+' V';$('#bIcsat').textContent=(q.icsat*1e3).toFixed(2)+' mA';$('#bPc').textContent=(q.pc*1000).toFixed(1)+' mW';const st=$('#bState');if(q.region==='cutoff'){st.className='status-card off';st.innerHTML='<b>CORTE</b><span>No hay excitación de base suficiente; el colector queda prácticamente sin corriente.</span>'}else if(q.region==='saturation'){st.className='status-card danger';st.innerHTML='<b>SATURACIÓN</b><span>El candidato β·IB supera la corriente que permite la malla de colector.</span>'}else{st.className='status-card ok';st.innerHTML='<b>REGIÓN ACTIVA</b><span>La malla de colector puede sostener la corriente β·IB y VCE permanece por encima de saturación.</span>'}drawLoad($('#bjtSimChart'),v,q,true)}
['bVbb','bRb','bVcc','bRc','bBeta','bVbe','bVces'].forEach(id=>$('#'+id)?.addEventListener('input',updateSim));updateSim();
$$('[data-bpred]').forEach(b=>b.addEventListener('click',()=>{const ok=b.dataset.bpred==='sat';window.AL.fb($('#bPredFb'),ok?'Correcto. Al disminuir RB aumenta IB y el punto de operación tiende hacia una mayor IC; si la malla de colector limita esa corriente, el transistor entra en saturación.':'Revisa IB=(VBB−VBE)/RB: al bajar RB aumenta IB y el transistor se desplaza hacia mayor conducción, no hacia corte.',ok)}));

const exercises=[
{Vbb:5,Rb:220,Vcc:12,Rc:2.7,beta:100,Vbe:.7,Vces:.2},
{Vbb:3.3,Rb:100,Vcc:9,Rc:1.8,beta:150,Vbe:.7,Vces:.2},
{Vbb:5,Rb:10,Vcc:5,Rc:1,beta:120,Vbe:.7,Vces:.2},
{Vbb:.4,Rb:47,Vcc:12,Rc:2.2,beta:100,Vbe:.7,Vces:.2},
{Vbb:2.5,Rb:82,Vcc:10,Rc:1.5,beta:80,Vbe:.7,Vces:.2},
{Vbb:5,Rb:330,Vcc:15,Rc:3.3,beta:180,Vbe:.7,Vces:.2}
];
let currentEx=null;function newEx(){currentEx=solve(exercises[Math.floor(Math.random()*exercises.length)]);$('#bExStatement').innerHTML=`Analiza un NPN con <b>VBB=${currentEx.Vbb} V</b>, <b>RB=${currentEx.Rb} kΩ</b>, <b>VCC=${currentEx.Vcc} V</b>, <b>RC=${currentEx.Rc} kΩ</b>, <b>β=${currentEx.beta}</b>, VBE=${currentEx.Vbe} V y VCE(sat)=${currentEx.Vces} V. Calcula IB, IC, VCE y determina la región.`;['bExIb','bExIc','bExVce'].forEach(id=>$('#'+id).value='');$('#bExRegion').value='';$('#bExFb').textContent='';$('#bExFb').className='feedback';window.AL.typeset($('#bExStatement'))}
$('#bExNew')?.addEventListener('click',newEx);$('#bExCheck')?.addEventListener('click',()=>{const ib=+$('#bExIb').value,ic=+$('#bExIc').value,vce=+$('#bExVce').value,r=$('#bExRegion').value;if(!Number.isFinite(ib)||!Number.isFinite(ic)||!Number.isFinite(vce)||!r){window.AL.fb($('#bExFb'),'Completa todos los resultados antes de comprobar.',false);return}const ok1=Math.abs(ib-currentEx.ib*1e6)<Math.max(.4,currentEx.ib*1e6*.02),ok2=Math.abs(ic-currentEx.ic*1e3)<Math.max(.05,currentEx.ic*1e3*.025),ok3=Math.abs(vce-currentEx.vce)<.08,ok4=r===currentEx.region;window.AL.fb($('#bExFb'),`${ok1?'IB ✓':'IB revisar'} · ${ok2?'IC ✓':'IC revisar'} · ${ok3?'VCE ✓':'VCE revisar'} · ${ok4?'región ✓':'región revisar'}. ${ok4?'':'Compara primero βIB con el límite de la malla de colector.'}`,ok1&&ok2&&ok3&&ok4)});newEx();

const prompts=[
{q:'Un estudiante afirma: “si el transistor tiene β=150, entonces IC=150·IB en cualquier condición”. Explica por qué la frase es incompleta.',g:'<b>Guía.</b> La relación IC≈βIB describe la región activa. Si la malla de colector no puede suministrar esa corriente, el BJT entra en saturación y la corriente queda limitada por VCC, RC y VCE(sat). Además β no es una constante exacta: cambia entre dispositivos y con el punto de operación.'},
{q:'Explica por qué una base físicamente delgada favorece que la corriente de colector sea mucho mayor que la corriente de base.',g:'<b>Guía.</b> Los portadores inyectados por el emisor atraviesan una base delgada; solo una fracción pequeña se recombina en ella. La mayor parte alcanza la región colectora, por lo que la corriente asociada al colector es mucho mayor que la corriente de base.'},
{q:'¿Por qué corte y saturación son regiones útiles para conmutación, mientras la región activa es la apropiada para amplificación lineal?',g:'<b>Guía.</b> En corte el transistor aproxima un interruptor abierto y en saturación un interruptor cerrado con VCE pequeño. En activa, cambios de la excitación de base producen cambios controlados de corriente de colector sin fijar el dispositivo en uno de los extremos.'},
{q:'Un datasheet da hFE=100–300 para una condición concreta. Explica por qué no es correcto diseñar un circuito crítico suponiendo hFE=300.',g:'<b>Guía.</b> El rango representa dispersión entre dispositivos y condiciones de prueba. Diseñar con el extremo más favorable puede fallar con otro transistor o a otra temperatura/corriente. Debe usarse margen y una topología de polarización adecuada.'}
];
let pi=0;function showPrompt(first=false){let n=Math.floor(Math.random()*prompts.length);if(!first&&prompts.length>1)while(n===pi)n=Math.floor(Math.random()*prompts.length);pi=n;$('#bOpenPrompt').innerHTML='<b>Situación:</b> '+prompts[pi].q;$('#bOpen').value='';$('#bOpenGuide').className='guide';$('#bOpenGuide').innerHTML='';window.AL.typeset($('#bOpenPrompt'))}$('#bOpenNew')?.addEventListener('click',()=>showPrompt(false));$('#bOpenGuideBtn')?.addEventListener('click',()=>{const g=$('#bOpenGuide');if(($('#bOpen').value.trim().length)<45){g.innerHTML='Escribe primero una explicación de varias líneas antes de consultar la guía.';g.className='guide show';return}g.innerHTML=prompts[pi].g;g.className='guide show';window.AL.typeset(g)});showPrompt(true);
})();