(()=>{"use strict";const {$,$$}=window.AL;

// Darlington explorer
function updateDarlington(){const b1=+$('#dB1').value,b2=+$('#dB2').value,ib=+$('#dIb').value*1e-6;const bd=b1*b2+b1+b2;const ic=bd*ib,ie2=(b1+1)*(b2+1)*ib;$('#dB1Txt').textContent=b1;$('#dB2Txt').textContent=b2;$('#dIbTxt').textContent=(ib*1e6).toFixed(1);$('#dGain').textContent=bd.toFixed(0);$('#dIc').textContent=(ic*1e3).toFixed(2)+' mA';$('#dIe').textContent=(ie2*1e3).toFixed(2)+' mA'}
['dB1','dB2','dIb'].forEach(id=>$('#'+id)?.addEventListener('input',updateDarlington));updateDarlington();

// Current mirror explorer
function updateMirror(){const V=+$('#mV').value,R=+$('#mR').value*1000,b=+$('#mB').value,Vbe=.7;const iref=Math.max(0,(V-Vbe)/R),io=b/(b+2)*iref,err=iref?100*(iref-io)/iref:0;$('#mVTxt').textContent=V.toFixed(1);$('#mRTxt').textContent=(R/1000).toFixed(1);$('#mBTxt').textContent=b;$('#mIref').textContent=(iref*1e3).toFixed(3)+' mA';$('#mIo').textContent=(io*1e3).toFixed(3)+' mA';$('#mErr').textContent=err.toFixed(2)+' %'}
['mV','mR','mB'].forEach(id=>$('#'+id)?.addEventListener('input',updateMirror));updateMirror();

// Driver checker
function updateDriver(){const V=+$('#drvV').value,I=+$('#drvI').value/1000,R=+$('#drvR').value,bTarget=+$('#drvB').value,Vbe=.8;const ib=Math.max(0,(V-Vbe)/R),forced=ib>0?I/ib:Infinity,margin=ib/(I/bTarget);$('#drvVTxt').textContent=V.toFixed(1);$('#drvITxt').textContent=(I*1000).toFixed(0);$('#drvRTxt').textContent=R.toFixed(0);$('#drvBTxt').textContent=bTarget;$('#drvIb').textContent=(ib*1000).toFixed(2)+' mA';$('#drvForced').textContent=forced.toFixed(1);$('#drvMargin').textContent=(margin*100).toFixed(0)+' %';const st=$('#drvState');if(margin>=1.15){st.className='status-card ok';st.innerHTML='<b>🟢 MARGEN ADECUADO</b><span>La corriente de base supera el objetivo de diseño seleccionado.</span>'}else if(margin>=.9){st.className='status-card knee';st.innerHTML='<b>🟡 CERCA DEL LÍMITE</b><span>El circuito está muy próximo al criterio de corriente de base. Revisa tolerancias y datasheet.</span>'}else{st.className='status-card danger';st.innerHTML='<b>🔴 CORRIENTE DE BASE INSUFICIENTE</b><span>No se cumple el β forzado seleccionado.</span>'}}
['drvV','drvI','drvR','drvB'].forEach(id=>$('#'+id)?.addEventListener('input',updateDriver));updateDriver();

// H bridge diagram
const HSTATES={forward:{on:['Q1','Q4'],txt:'AVANCE',msg:'La corriente atraviesa Q1 → motor → Q4.',cls:'ok',dir:'→'},reverse:{on:['Q2','Q3'],txt:'REVERSA',msg:'La corriente atraviesa Q2 → motor → Q3.',cls:'ok',dir:'←'},coast:{on:[],txt:'LIBRE',msg:'Los cuatro BJT están OFF; el motor queda sin excitación activa.',cls:'off',dir:'○'},shoot:{on:['Q1','Q3'],txt:'SHOOT-THROUGH',msg:'Q1 y Q3 conectan la misma rama de la fuente a tierra. Estado prohibido.',cls:'danger',dir:'⚠'}};
function drawBridge(key='forward'){const s=HSTATES[key],el=$('#hBridgeSvg');if(!el)return;const on=q=>s.on.includes(q);const box=(q,x,y,type)=>`<rect x="${x}" y="${y}" width="110" height="54" rx="12" fill="${on(q)?'var(--green2)':(type==='high'?'var(--rose2)':'var(--blue2)')}" stroke="${on(q)?'var(--green)':(type==='high'?'var(--red)':'var(--blue)')}" stroke-width="3"/><text x="${x+55}" y="${y+33}" text-anchor="middle" class="svg-title">${q}</text>`;el.innerHTML=`<rect width="760" height="420" rx="14" fill="var(--paper)"/><text x="380" y="34" text-anchor="middle" class="svg-title">Puente H — estado interactivo</text><text x="380" y="58" text-anchor="middle" class="svgtext">Verde = transistor activo en el estado seleccionado</text><line x1="140" y1="88" x2="620" y2="88" class="wire strong"/><text x="628" y="92" class="svgtext">+VCC</text>${box('Q1',160,118,'high')}${box('Q2',490,118,'high')}${box('Q3',160,286,'low')}${box('Q4',490,286,'low')}<line x1="215" y1="88" x2="215" y2="118" class="wire"/><line x1="545" y1="88" x2="545" y2="118" class="wire"/><line x1="215" y1="172" x2="215" y2="210" class="wire"/><line x1="545" y1="172" x2="545" y2="210" class="wire"/><line x1="215" y1="286" x2="215" y2="252" class="wire"/><line x1="545" y1="286" x2="545" y2="252" class="wire"/><line x1="215" y1="210" x2="315" y2="210" class="wire"/><line x1="445" y1="210" x2="545" y2="210" class="wire"/><line x1="215" y1="252" x2="315" y2="252" class="wire"/><line x1="445" y1="252" x2="545" y2="252" class="wire"/><circle cx="380" cy="231" r="62" fill="var(--green2)" stroke="var(--green)" stroke-width="4"/><text x="380" y="220" text-anchor="middle" class="svg-title">MOTOR</text><text x="380" y="250" text-anchor="middle" class="svg-title">${s.dir}</text><line x1="215" y1="340" x2="215" y2="370" class="wire"/><line x1="545" y1="340" x2="545" y2="370" class="wire"/><line x1="215" y1="370" x2="545" y2="370" class="wire strong"/><text x="380" y="404" text-anchor="middle" class="svg-title">GND</text>`;const st=$('#hBridgeState');st.className='status-card '+s.cls;st.innerHTML=`<b>${s.txt}</b><span>${s.msg}</span>`}
$$('[data-hstate]').forEach(b=>b.addEventListener('click',()=>drawBridge(b.dataset.hstate)));drawBridge('forward');

// Random numeric challenge
const challenges=[
 {q:'Relé: 12 V, Rbobina=180 Ω, VCE(sat)=0.2 V. Calcula la corriente de bobina en mA.',ans:(12-.2)/180*1000,tol:.7,unit:'mA',choice:'ok',why:'Se resuelve primero la malla de carga. Después se diseña la base y se verifica el GPIO.'},
 {q:'Driver: IC=240 mA y βF=10. Calcula la corriente de base mínima en mA.',ans:24,tol:.3,unit:'mA',choice:'review',why:'El cálculo es correcto, pero esa corriente puede ser demasiado alta para un GPIO. El siguiente paso es revisar la interfaz de control.'},
 {q:'Espejo: VCC=10 V, RREF=4.7 kΩ, VBE=0.7 V, β=100. Calcula IO en mA incluyendo dos corrientes de base.',ans:(100/102)*((10-.7)/4700)*1000,tol:.03,unit:'mA',choice:'ok',why:'Usa IO=β/(β+2)·IREF y confirma que el transistor de salida permanezca en activa.'},
 {q:'Puente H: VCC=12 V y cada transistor conduce con 0.30 V de caída. Calcula VM en avance.',ans:11.4,tol:.03,unit:'V',choice:'ok',why:'Conducen dos dispositivos en serie con el motor: uno del lado alto y otro del lado bajo.'},
 {q:'TIP122: para IC=1.2 A y βF=250, calcula IB requerida en mA.',ans:4.8,tol:.05,unit:'mA',choice:'review',why:'La corriente de base debe compararse con la capacidad de la interfaz y con las condiciones de saturación del datasheet.'},
 {q:'Darlington: β1=50, β2=100. Calcula βD exacta = β1β2+β1+β2.',ans:5150,tol:1,unit:'',choice:'ok',why:'La aproximación β1β2 daría 5000; el valor exacto del modelo simple es 5150.'},
 {q:'Potencia: un BJT conduce 1.2 A con VCE=0.60 V. Calcula la disipación en W.',ans:.72,tol:.01,unit:'W',choice:'review',why:'P≈VCE·IC. Después de obtener la potencia debes revisar temperatura y SOA.'},
 {q:'Térmica: P=0.72 W y RθJA=62.5 °C/W. Calcula el incremento de temperatura ΔT.',ans:45,tol:.3,unit:'°C',choice:'review',why:'ΔT≈P·RθJA. La estimación térmica no sustituye la revisión del datasheet ni de transitorios.'},
 {q:'Acoplamiento directo: VX=6.95 V, VBE2=0.7 V y RE2=820 Ω. Calcula IE2 en mA.',ans:(6.95-.7)/820*1000,tol:.03,unit:'mA',choice:'ok',why:'En el seguidor, VE2≈VX−VBE y luego IE2=VE2/RE2.'},
 {q:'Motor: 1.4 A de arranque y βF=250. Calcula IB requerida en mA.',ans:5.6,tol:.05,unit:'mA',choice:'review',why:'La corriente de arranque es la condición crítica; compárala con el límite real de la interfaz.'}
];let currentChallenge=null;
function newChallenge(){currentChallenge=challenges[Math.floor(Math.random()*challenges.length)];$('#cExStatement').textContent=currentChallenge.q;$('#cExUnit').textContent=currentChallenge.unit;$('#cExValue').value='';$('#cExChoice').value='';$('#cExFb').textContent='';$('#cExFb').className='feedback';window.AL.typeset($('#cExStatement'))}
$('#cExNew')?.addEventListener('click',newChallenge);$('#cExCheck')?.addEventListener('click',()=>{const v=parseFloat($('#cExValue').value),c=$('#cExChoice').value;if(!Number.isFinite(v)||!c){window.AL.fb($('#cExFb'),'Completa el valor y la conclusión.',false);return}const okV=Math.abs(v-currentChallenge.ans)<=currentChallenge.tol,okC=c===currentChallenge.choice;window.AL.fb($('#cExFb'),`${okV?'valor ✓':'valor revisar'} · ${okC?'criterio ✓':'criterio revisar'}. ${currentChallenge.why}`,okV&&okC)});newChallenge();

// Theory vs simulation
$('#cmpCheck')?.addEventListener('click',()=>{const t=parseFloat($('#cmpTheo').value),s=parseFloat($('#cmpSim').value),out=$('#cmpTraffic');if(!Number.isFinite(t)||!Number.isFinite(s)){out.className='traffic-result red';out.innerHTML='<b>🔴 Faltan datos.</b> Registra el mismo parámetro teórico y simulado.';return}const den=Math.max(Math.abs(t),1e-12),e=Math.abs(s-t)/den*100;if(e<=5){out.className='traffic-result green';out.innerHTML=`<b>🟢 ${e.toFixed(2)} %.</b> Buena concordancia. Explica las diferencias de modelo.`}else if(e<=15){out.className='traffic-result yellow';out.innerHTML=`<b>🟡 ${e.toFixed(2)} %.</b> Diferencia apreciable: revisa β, VBE, VCE(sat), unidades y condiciones de prueba.`}else{out.className='traffic-result red';out.innerHTML=`<b>🔴 ${e.toFixed(2)} %.</b> Revisa región de operación, conexiones, modelo y valores antes de aceptar el resultado.`}});

// Open prompts
const prompts=[
 {q:'Un motor funciona correctamente una vez que gira, pero el transistor se calienta o falla en el arranque. Explica qué dato del motor probablemente se ignoró y cómo cambia el diseño.',g:'<b>Guía.</b> La corriente de arranque o de rotor bloqueado puede ser varias veces la nominal. Esa corriente aumenta la exigencia de base, la caída de saturación y la disipación. El diseño debe verificarse en esa condición crítica.'},
 {q:'¿Por qué un TIP122 con hFE muy alto puede necesitar más corriente de base de la que sugiere IC/hFE para garantizar conmutación?',g:'<b>Guía.</b> hFE caracteriza la región activa bajo condiciones específicas. La saturación se especifica con pares IC/IB concretos, equivalentes a un β forzado mucho menor. Mezclar ambos parámetros lleva a diseños no garantizados.'},
 {q:'Explica por qué el segundo transistor de una red acoplada directamente puede modificar el punto Q del primero.',g:'<b>Guía.</b> La base de la segunda etapa toma corriente del mismo nodo que antes se consideraba solo salida de la primera. Esa corriente adicional produce caída extra en la resistencia de colector y desplaza el voltaje del nodo.'},
 {q:'¿Por qué un espejo de corriente simple deja de copiar bien la corriente cuando el voltaje de salida es demasiado bajo?',g:'<b>Guía.</b> El transistor de salida necesita permanecer en activa. Con VCE demasiado pequeño entra en saturación y la relación controlada por VBE deja de producir la corriente esperada.'},
 {q:'En un puente H, explica por qué el estado shoot-through es distinto de un frenado intencional.',g:'<b>Guía.</b> El shoot-through activa dispositivos de la misma rama y crea una ruta directa de fuente a tierra. El frenado controlado usa estados específicos para imponer una condición al motor sin cortocircuitar la alimentación.'},
 {q:'Una hoja de datos indica IC(max)=6 A. Explica por qué ese número por sí solo no autoriza a conmutar 6 A continuamente.',g:'<b>Guía.</b> Deben revisarse VCE(sat), potencia, temperatura, SOA, condiciones del máximo, corriente de base, encapsulado y disipación. Los máximos absolutos no son puntos recomendados de diseño.'}
];let pidx=0;function showPrompt(first=false){let n=Math.floor(Math.random()*prompts.length);if(!first&&prompts.length>1)while(n===pidx)n=Math.floor(Math.random()*prompts.length);pidx=n;$('#cOpenPrompt').innerHTML='<b>Situación:</b> '+prompts[n].q;$('#cOpen').value='';$('#cOpenGuide').className='guide';$('#cOpenGuide').innerHTML='';window.AL.typeset($('#cOpenPrompt'))}
$('#cOpenNew')?.addEventListener('click',()=>showPrompt(false));$('#cOpenGuideBtn')?.addEventListener('click',()=>{const g=$('#cOpenGuide');if($('#cOpen').value.trim().length<55){g.innerHTML='Desarrolla primero tu argumento en varias líneas y luego consulta la guía.';g.className='guide show';return}g.innerHTML=prompts[pidx].g;g.className='guide show';window.AL.typeset(g)});showPrompt(true);
})();