
(()=>{"use strict";const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];window.AL={$, $$};
const KEY='analoglab-complete-v4',done=new Set(JSON.parse(localStorage.getItem(KEY)||'[]'));
function progress(){const marks=$$('[data-mark]');marks.forEach(b=>{const y=done.has(b.dataset.mark);b.classList.toggle('done',y);b.textContent=y?'✓ Estudiado':'Marcar estudiado'});const total=16,p=Math.min(100,Math.round(done.size/total*100));$$('.progress-value').forEach(e=>e.textContent=p+'%');$$('.progress-fill').forEach(e=>e.style.width=p+'%');localStorage.setItem(KEY,JSON.stringify([...done]));window.dispatchEvent(new CustomEvent('al-progress',{detail:{count:done.size,pct:p}}))}
$$('[data-mark]').forEach(b=>b.addEventListener('click',()=>{done.has(b.dataset.mark)?done.delete(b.dataset.mark):done.add(b.dataset.mark);progress()}));progress();window.AL.done=done;window.AL.progress=progress;
const menu=$('.menu'),side=$('aside');if(menu&&side){menu.addEventListener('click',()=>side.classList.toggle('open'));$$('aside nav a').forEach(a=>a.addEventListener('click',()=>side.classList.remove('open')))}
$('#theme')?.addEventListener('click',()=>document.body.classList.toggle('dark'));$('#class')?.addEventListener('click',()=>{document.body.classList.toggle('classmode');$('#class').textContent=document.body.classList.contains('classmode')?'Salir modo clase':'Modo clase'});
const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)$$('aside nav a').forEach(a=>a.classList.toggle('current',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-28% 0px -64% 0px'});$$('.module[id]').forEach(m=>ob.observe(m));
function fb(el,msg,ok){el.textContent=msg;el.className='feedback '+(ok?'ok':'bad')}
window.AL.fb=fb;
function renderQuiz(el){const key=el.dataset.quiz,bank=window.ANALOG_QUIZZES?.[key]||[];if(!bank.length)return;let order=bank.map((_,i)=>i).sort(()=>Math.random()-.5),i=0,score=0,locked=false;el.innerHTML='<h3>Comprobación del módulo</h3><div class="quiz-head"><span class="qcount"></span><span class="qscore"></span></div><h4 class="question"></h4><div class="options"></div><p class="feedback qfb"></p><div class="buttons"><button class="btn small next" disabled>Siguiente</button><button class="btn small reset">Nuevo conjunto</button></div>';const qcount=$('.qcount',el),qscore=$('.qscore',el),question=$('.question',el),opts=$('.options',el),qfb=$('.qfb',el),next=$('.next',el);function show(){locked=false;const q=bank[order[i]];qcount.textContent=`Pregunta ${i+1} de ${bank.length}`;qscore.textContent=`Aciertos: ${score}`;question.textContent=q.q;qfb.textContent='';qfb.className='feedback';next.disabled=true;opts.innerHTML=q.options.map((o,j)=>`<button data-i="${j}">${String.fromCharCode(65+j)}. ${o.text}</button>`).join('');$$('button',opts).forEach(b=>b.addEventListener('click',()=>{if(locked)return;locked=true;const j=+b.dataset.i,ok=j===q.answer;if(ok)score++;fb(qfb,q.options[j].feedback,ok);qscore.textContent=`Aciertos: ${score}`;next.disabled=false}))}next.addEventListener('click',()=>{i++;if(i>=bank.length){question.textContent=`Resultado: ${score}/${bank.length}`;opts.innerHTML='';qfb.textContent=score===bank.length?'Dominio completo del bloque.':score>=Math.ceil(bank.length*.75)?'Buen dominio. Revisa las explicaciones de las respuestas incorrectas.':'Conviene regresar a la teoría y a los ejemplos antes de repetir.';next.disabled=true}else show()});$('.reset',el).addEventListener('click',()=>{order=bank.map((_,j)=>j).sort(()=>Math.random()-.5);i=0;score=0;show()});show()}
$$('[data-quiz]').forEach(renderQuiz);window.AL.renderQuiz=renderQuiz;
$$('[data-step]').forEach(card=>{let steps=JSON.parse(card.dataset.steps||'[]'),i=0,btn=$('.step-btn',card),out=$('.step-out',card);btn?.addEventListener('click',()=>{if(i===0&&out.dataset.end){out.innerHTML='';out.dataset.end=''}out.innerHTML+=`<div class="solution-step"><b>Paso ${i+1}.</b> ${steps[i]}</div>`;i++;if(i>=steps.length){i=0;out.dataset.end='1';btn.textContent='Reiniciar'}else btn.textContent=`Mostrar paso ${i+1}`})});
window.AL.axes=(xmin,xmax,ymin,ymax,xlab,ylab)=>{const W=760,H=400,L=64,R=24,T=23,B=51,gw=W-L-R,gh=H-T-B,x=v=>L+(v-xmin)/(xmax-xmin)*gw,y=v=>T+gh-(v-ymin)/(ymax-ymin)*gh;let h=`<rect width="${W}" height="${H}" rx="12" fill="var(--paper)"/>`;if(ymin<=0&&ymax>=0)h+=`<line x1="${L}" y1="${y(0)}" x2="${L+gw}" y2="${y(0)}" stroke="currentColor"/>`;if(xmin<=0&&xmax>=0)h+=`<line x1="${x(0)}" y1="${T}" x2="${x(0)}" y2="${T+gh}" stroke="currentColor"/>`;for(let k=0;k<=4;k++){let xv=xmin+(xmax-xmin)*k/4,yv=ymin+(ymax-ymin)*k/4;h+=`<text x="${x(xv)}" y="${T+gh+20}" text-anchor="middle" fill="currentColor" font-size="11">${xv.toFixed(Math.abs(xmax-xmin)<3?2:1)}</text><text x="${L-8}" y="${y(yv)+4}" text-anchor="end" fill="currentColor" font-size="11">${yv.toFixed(1)}</text>`}h+=`<text x="${L+gw/2}" y="${H-8}" text-anchor="middle" fill="currentColor" font-size="13">${xlab}</text><text x="17" y="${T+gh/2}" transform="rotate(-90 17 ${T+gh/2})" text-anchor="middle" fill="currentColor" font-size="13">${ylab}</text>`;return{W,H,L,R,T,B,gw,gh,x,y,h}}
})();
